#!/usr/bin/env python3
"""
Compare 2D slice-based metrics vs 3D axon-based metrics.

This script creates a two-subplot comparison plot showing:
- Subplot 1: Arithmetic mean radius (2D vs 3D)
- Subplot 2: Effective radius (2D vs 3D)

For 2D values: mean ± std across slices (with error bars)
For 3D values: single pooled value (reference)

X-axis: 3D reference value
Y-axis: 2D value with error bars

Population Filtering:
Can optionally filter analysis to specific populations (CC/CG) using
JSON files generated by identify_cc_cg_populations.py.
"""

import argparse
import json
import logging
import re
from pathlib import Path
from typing import Dict, Tuple, Optional, Set, List

import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


def load_population_labels(json_file: Path, population_name: str) -> Set[int]:
    """
    Load axon labels for a specific population from JSON file.

    Args:
        json_file: Path to populations JSON file (from identify_cc_cg_populations.py)
        population_name: Population name ('cc' or 'cg')

    Returns:
        Set of axon label integers for the specified population
    """
    with open(json_file, 'r') as f:
        data = json.load(f)

    for pop in data['populations']:
        if pop['name'].lower() == population_name.lower():
            labels = set(pop['axon_labels'])
            logger.info(f"Loaded {len(labels)} axon labels for population '{population_name}' from {json_file.name}")
            logger.info(f"  Dominant axis: {pop.get('dominant_axis_name', 'N/A')}")
            return labels

    raise ValueError(f"Population '{population_name}' not found in {json_file}")


def compute_r_eff(radii: np.ndarray) -> float:
    """
    Compute effective MRI-visible radius: r_eff = (⟨r⁶⟩/⟨r²⟩)^(1/4)

    Args:
        radii: Array of radius values in micrometers

    Returns:
        Effective radius in micrometers
    """
    if len(radii) == 0:
        return np.nan

    r2 = radii ** 2
    r6 = radii ** 6

    r2_mean = np.mean(r2)
    r6_mean = np.mean(r6)

    if r2_mean == 0:
        return np.nan

    return (r6_mean / r2_mean) ** 0.25


def load_2d_metrics(npz_file: Path, radius_type: str = 'minor') -> Dict[str, float]:
    """
    Load 2D slice-based metrics from NPZ file.

    Computes:
    - Arithmetic mean radius: median across slices with 95% CI
    - Effective radius: median across slices with 95% CI

    Args:
        npz_file: Path to 2D slice profiles NPZ file
        radius_type: 'circular' (from area) or 'minor' (from ellipse), default: 'minor'

    Returns:
        Dictionary with keys: mean_radius, mean_radius_lo, mean_radius_hi,
                              r_eff, r_eff_lo, r_eff_hi
    """
    data = np.load(npz_file)

    # Extract data based on radius_type
    bin_centers = data['bin_centers']

    if radius_type == 'minor':
        # Load minor axis histograms
        histograms = data['histograms_minor']  # Shape: (n_slices, n_bins)
        r_eff_per_slice = data['r_eff_minor_per_slice']
    else:  # circular
        # Load circular-equivalent histograms
        histograms = data['histograms_circular']  # Shape: (n_slices, n_bins)
        r_eff_per_slice = data['r_eff_circular_per_slice']

    # Compute per-slice arithmetic mean
    mean_radius_per_slice = []
    for hist_slice in histograms:
        counts = hist_slice.sum()
        if counts > 0:
            mean_r = np.sum(bin_centers * hist_slice) / counts
            mean_radius_per_slice.append(mean_r)

    mean_radius_per_slice = np.array(mean_radius_per_slice)

    # Compute median and IQR (25th-75th percentile) for mean radius
    if len(mean_radius_per_slice) > 0:
        mean_radius_median = np.median(mean_radius_per_slice)
        mean_radius_lo = np.percentile(mean_radius_per_slice, 25)
        mean_radius_hi = np.percentile(mean_radius_per_slice, 75)
    else:
        mean_radius_median = np.nan
        mean_radius_lo = np.nan
        mean_radius_hi = np.nan

    # Compute median and IQR for effective radius
    valid_r_eff = r_eff_per_slice[r_eff_per_slice > 0]
    if len(valid_r_eff) > 0:
        r_eff_median = np.median(valid_r_eff)
        r_eff_lo = np.percentile(valid_r_eff, 25)
        r_eff_hi = np.percentile(valid_r_eff, 75)
    else:
        r_eff_median = np.nan
        r_eff_lo = np.nan
        r_eff_hi = np.nan

    logger.info(f"2D metrics from {npz_file.name}:")
    logger.info(f"  Mean radius: {mean_radius_median:.3f} [{mean_radius_lo:.3f}, {mean_radius_hi:.3f}] μm")
    logger.info(f"  Effective radius: {r_eff_median:.3f} [{r_eff_lo:.3f}, {r_eff_hi:.3f}] μm")

    return {
        'mean_radius': mean_radius_median,
        'mean_radius_lo': mean_radius_lo,
        'mean_radius_hi': mean_radius_hi,
        'r_eff': r_eff_median,
        'r_eff_lo': r_eff_lo,
        'r_eff_hi': r_eff_hi
    }


def load_3d_metrics(npz_file: Path, population_labels: Optional[Set[int]] = None) -> Dict[str, float]:
    """
    Load 3D axon-based metrics from NPZ file.

    Computes:
    - Arithmetic mean radius (from all_radii_um or filtered by population)
    - Effective radius (from all_radii_um or filtered by population)

    Args:
        npz_file: Path to 3D axon profiles NPZ file
        population_labels: Optional set of axon labels to filter by

    Returns:
        Dictionary with keys: mean_radius, r_eff
    """
    data = np.load(npz_file, allow_pickle=True)

    if population_labels is not None:
        # Filter by population
        axon_labels = data['labels']
        radii_profiles = data['radii_profiles_um']  # Object array with per-axon profiles

        # Collect radii only for axons in the population
        filtered_radii_list = []
        n_matched = 0
        for i, label in enumerate(axon_labels):
            if int(label) in population_labels:
                filtered_radii_list.append(radii_profiles[i])
                n_matched += 1

        if n_matched == 0:
            raise ValueError(f"No axons from population found in {npz_file.name}")

        all_radii = np.concatenate(filtered_radii_list)
        logger.info(f"3D metrics from {npz_file.name} (filtered to {n_matched}/{len(axon_labels)} axons):")
    else:
        # Use all radii
        all_radii = data['all_radii_um']
        logger.info(f"3D metrics from {npz_file.name}:")

    # Compute arithmetic mean
    mean_radius = np.mean(all_radii)

    # Compute effective radius
    r_eff = compute_r_eff(all_radii)

    logger.info(f"  Mean radius: {mean_radius:.3f} μm")
    logger.info(f"  Effective radius: {r_eff:.3f} μm")
    logger.info(f"  Total samples: {len(all_radii)}")

    return {
        'mean_radius': mean_radius,
        'r_eff': r_eff
    }


def extract_group_info(sample_name: str) -> Tuple[str, str]:
    """
    Extract group (TBI/Sham) and population (CC/CG/None) from sample name.

    Args:
        sample_name: Sample name like "sham_25_ipsi_CC", "tbi_2_contra", etc.

    Returns:
        Tuple of (group, population) where:
        - group: "TBI" or "Sham"
        - population: "CC", "CG", or None
    """
    name_lower = sample_name.lower()

    # Determine group
    if 'tbi' in name_lower:
        group = "TBI"
    elif 'sham' in name_lower:
        group = "Sham"
    else:
        group = "Unknown"

    # Determine population (from suffix)
    if sample_name.endswith('_CC'):
        population = "CC"
    elif sample_name.endswith('_CG'):
        population = "CG"
    else:
        population = None

    return group, population


def plot_combined_2d_vs_3d_comparison(
    all_metrics: list[tuple[Dict[str, float], Dict[str, float], str]],
    output_file: Path,
    title: str = "2D vs 3D Metrics Comparison"
) -> None:
    """
    Create two-subplot comparison plot with ALL samples combined.

    Subplot 1: Arithmetic mean radius (all samples)
    Subplot 2: Effective radius (all samples)

    Each point represents one sample with error bars.
    Color coding: Blue=Sham, Red=TBI
    Marker coding: Circle=CC, Triangle=CG, Square=No population

    Args:
        all_metrics: List of (metrics_2d, metrics_3d, sample_name) tuples
        output_file: Output PNG file path
        title: Overall plot title
    """
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

    # Color and marker mappings
    group_colors = {'Sham': '#1f77b4', 'TBI': '#d62728', 'Unknown': '#7f7f7f'}  # Blue, Red, Gray
    pop_markers = {'CC': 'o', 'CG': '^', None: 's'}  # Circle, Triangle, Square

    # Organize data by group and population
    data_by_category = {}

    for metrics_2d, metrics_3d, sample_name in all_metrics:
        group, population = extract_group_info(sample_name)
        category = (group, population)

        if category not in data_by_category:
            data_by_category[category] = {
                'x_mean': [], 'y_mean': [], 'yerr_mean_lo': [], 'yerr_mean_hi': [],
                'x_eff': [], 'y_eff': [], 'yerr_eff_lo': [], 'yerr_eff_hi': []
            }

        # Mean radius (asymmetric error bars: distance from median to lo/hi)
        data_by_category[category]['x_mean'].append(metrics_3d['mean_radius'])
        data_by_category[category]['y_mean'].append(metrics_2d['mean_radius'])
        data_by_category[category]['yerr_mean_lo'].append(metrics_2d['mean_radius'] - metrics_2d['mean_radius_lo'])
        data_by_category[category]['yerr_mean_hi'].append(metrics_2d['mean_radius_hi'] - metrics_2d['mean_radius'])

        # Effective radius (asymmetric error bars)
        data_by_category[category]['x_eff'].append(metrics_3d['r_eff'])
        data_by_category[category]['y_eff'].append(metrics_2d['r_eff'])
        data_by_category[category]['yerr_eff_lo'].append(metrics_2d['r_eff'] - metrics_2d['r_eff_lo'])
        data_by_category[category]['yerr_eff_hi'].append(metrics_2d['r_eff_hi'] - metrics_2d['r_eff'])

    # Collect all data for axis limits and correlation
    all_x_mean, all_y_mean = [], []
    all_x_eff, all_y_eff = [], []

    # Plot each category
    for (group, population), data in sorted(data_by_category.items()):
        color = group_colors.get(group, '#7f7f7f')
        marker = pop_markers.get(population, 's')

        # Create label
        if population:
            label = f"{group} - {population}"
        else:
            label = group

        # Subplot 1: Mean radius (asymmetric error bars for 95% CI)
        yerr_mean = [data['yerr_mean_lo'], data['yerr_mean_hi']]
        ax1.errorbar(
            data['x_mean'], data['y_mean'], yerr=yerr_mean,
            fmt=marker, color=color, markersize=9,
            capsize=4, capthick=1.2, elinewidth=1.2,
            markeredgecolor='black', markeredgewidth=0.5,
            alpha=0.7, label=label
        )
        all_x_mean.extend(data['x_mean'])
        all_y_mean.extend(data['y_mean'])

        # Subplot 2: Effective radius (asymmetric error bars for 95% CI)
        yerr_eff = [data['yerr_eff_lo'], data['yerr_eff_hi']]
        ax2.errorbar(
            data['x_eff'], data['y_eff'], yerr=yerr_eff,
            fmt=marker, color=color, markersize=9,
            capsize=4, capthick=1.2, elinewidth=1.2,
            markeredgecolor='black', markeredgewidth=0.5,
            alpha=0.7, label=label
        )
        all_x_eff.extend(data['x_eff'])
        all_y_eff.extend(data['y_eff'])

    # Compute correlations
    r_mean, p_mean = stats.pearsonr(all_x_mean, all_y_mean)
    r_eff, p_eff = stats.pearsonr(all_x_eff, all_y_eff)

    # === Subplot 1: Arithmetic Mean Radius ===
    all_vals_mean = all_x_mean + all_y_mean
    min_val_mean = min(all_vals_mean) * 0.95
    max_val_mean = max(all_vals_mean) * 1.05

    ax1.plot([min_val_mean, max_val_mean], [min_val_mean, max_val_mean],
             'k--', alpha=0.5, linewidth=1.5, label='Identity', zorder=0)

    ax1.set_xlim(min_val_mean, max_val_mean)
    ax1.set_ylim(min_val_mean, max_val_mean)
    ax1.set_aspect('equal')
    ax1.grid(True, alpha=0.3, zorder=0)
    ax1.set_xlabel('3D Mean Radius (μm)', fontsize=12, fontweight='bold')
    ax1.set_ylabel('2D Mean Radius, median [IQR] (μm)', fontsize=12, fontweight='bold')

    # Add correlation to title
    title_mean = f'Arithmetic Mean Radius\nr = {r_mean:.3f}, p = {p_mean:.2e}'
    ax1.set_title(title_mean, fontsize=12, fontweight='bold')
    ax1.legend(loc='upper left', fontsize=9, framealpha=0.9)

    # === Subplot 2: Effective Radius ===
    all_vals_eff = all_x_eff + all_y_eff
    min_val_eff = min(all_vals_eff) * 0.95
    max_val_eff = max(all_vals_eff) * 1.05

    ax2.plot([min_val_eff, max_val_eff], [min_val_eff, max_val_eff],
             'k--', alpha=0.5, linewidth=1.5, label='Identity', zorder=0)

    ax2.set_xlim(min_val_eff, max_val_eff)
    ax2.set_ylim(min_val_eff, max_val_eff)
    ax2.set_aspect('equal')
    ax2.grid(True, alpha=0.3, zorder=0)
    ax2.set_xlabel('3D Effective Radius (μm)', fontsize=12, fontweight='bold')
    ax2.set_ylabel('2D Effective Radius, median [IQR] (μm)', fontsize=12, fontweight='bold')

    # Add correlation to title
    title_eff = f'Effective Radius (r_eff)\nr = {r_eff:.3f}, p = {p_eff:.2e}'
    ax2.set_title(title_eff, fontsize=12, fontweight='bold')
    ax2.legend(loc='upper left', fontsize=9, framealpha=0.9)

    # Overall title
    fig.suptitle(title, fontsize=14, fontweight='bold', y=0.98)

    plt.tight_layout()

    # Save figure
    output_file.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_file, dpi=200, bbox_inches='tight')
    plt.close()

    logger.info(f"Saved combined plot to {output_file}")
    logger.info(f"Correlations: Mean radius r={r_mean:.3f} (p={p_mean:.2e}), Effective radius r={r_eff:.3f} (p={p_eff:.2e})")


def find_matching_pairs(pattern_2d: str, pattern_3d: str) -> tuple[list[tuple[Path, Path, str]], list[Path], list[Path]]:
    """
    Find matching pairs of 2D and 3D profile files using glob patterns.

    Handles both standard naming and population-specific naming:
    - Standard: sample_slice_profiles.npz + sample_axon_profiles.npz
    - Population: sample_cc_slice_profiles.npz + sample_axon_profiles.npz
                  sample_cg_slice_profiles.npz + sample_axon_profiles.npz

    Args:
        pattern_2d: Glob pattern for 2D slice profile files (e.g., "data/processed/HM/*_slice_profiles.npz")
        pattern_3d: Glob pattern for 3D axon profile files (e.g., "data/processed/HM/*_axon_profiles.npz")

    Returns:
        Tuple of (matched_pairs, unmatched_2d, unmatched_3d) where:
        - matched_pairs: List of (2d_file, 3d_file, sample_name) tuples
        - unmatched_2d: List of 2D files without matching 3D file
        - unmatched_3d: List of 3D files without matching 2D file
    """
    import glob as glob_module
    import re

    slice_files = sorted([Path(f) for f in glob_module.glob(pattern_2d, recursive=True)])
    axon_files = sorted([Path(f) for f in glob_module.glob(pattern_3d, recursive=True)])

    # Build mappings
    # For 2D files: extract base name and population (if present)
    # Format: <base>_<pop>_slice_profiles.npz OR <base>_slice_profiles.npz
    slice_map = {}  # base_name -> {pop_name: file_path}

    for f in slice_files:
        stem = f.stem
        # Try population-specific format first: <base>_<pop>_slice_profiles
        match = re.match(r'(.+)_(cc|cg)_slice_profiles$', stem)
        if match:
            base_name = match.group(1)
            pop_name = match.group(2)
            if base_name not in slice_map:
                slice_map[base_name] = {}
            slice_map[base_name][pop_name] = f
        else:
            # Standard format: <base>_slice_profiles
            base_name = stem.replace('_slice_profiles', '')
            if base_name not in slice_map:
                slice_map[base_name] = {}
            slice_map[base_name]['all'] = f

    # For 3D files: simple base name extraction
    axon_map = {f.stem.replace('_axon_profiles', ''): f for f in axon_files}

    # Match: for each 2D file, find corresponding 3D file
    pairs = []
    matched_3d_files = set()

    for base_name, pop_dict in slice_map.items():
        if base_name in axon_map:
            axon_file = axon_map[base_name]
            matched_3d_files.add(axon_file)

            for pop_name, slice_file in pop_dict.items():
                if pop_name == 'all':
                    sample_name = base_name
                else:
                    sample_name = f"{base_name}_{pop_name.upper()}"

                pairs.append((slice_file, axon_file, sample_name))

    # Find unmatched files
    matched_2d_files = {f for pop_dict in slice_map.values() for f in pop_dict.values() if any(base_name in axon_map for base_name in slice_map.keys())}
    unmatched_2d = [f for f in slice_files if f not in matched_2d_files]
    unmatched_3d = [f for f in axon_files if f not in matched_3d_files]

    return pairs, unmatched_2d, unmatched_3d


def main():
    """Main entry point with CLI argument parsing."""
    parser = argparse.ArgumentParser(
        description='Compare 2D slice-based metrics vs 3D axon-based metrics',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Single file mode
  python plot_2d_versus_3d_metrics.py \\
      data/processed/HM/sham_25_ipsi_slice_profiles.npz \\
      data/processed/HM/sham_25_ipsi_axon_profiles.npz \\
      fig/sham_25_ipsi_comparison.png

  # Batch mode with glob patterns (creates single combined plot)
  python plot_2d_versus_3d_metrics.py \\
      "data/processed/HM/*_slice_profiles.npz" \\
      "data/processed/HM/*_axon_profiles.npz" \\
      fig/combined_2d_vs_3d_comparison.png

  # Analyze all populations separately (each as separate data point)
  python plot_2d_versus_3d_metrics.py \\
      "data/processed/LM/*_slice_profiles.npz" \\
      "data/processed/LM/*_axon_profiles.npz" \\
      fig/lm_all_populations_comparison.png \\
      --populations data/processed/LM/LM_25_ipsi_populations.json

  # Analyze single population (CC only)
  python plot_2d_versus_3d_metrics.py \\
      "data/processed/LM/*_slice_profiles.npz" \\
      "data/processed/LM/*_axon_profiles.npz" \\
      fig/cc_comparison.png \\
      --populations data/processed/LM/LM_25_ipsi_populations.json \\
      --population-name cc
        """
    )

    parser.add_argument('input', type=str,
                        help='Input: 2D NPZ file OR glob pattern for 2D slice profiles')
    parser.add_argument('output', type=str,
                        help='Output: 3D NPZ file (single mode) OR glob pattern for 3D axon profiles (batch mode)')
    parser.add_argument('output_dir', type=Path, nargs='?', default=None,
                        help='Output PNG file (single mode or batch with specific filename) OR output directory (batch mode with default filename)')
    parser.add_argument('--sample-name', type=str, default="",
                        help='Sample name for plot title (default: auto-detect from filename)')
    parser.add_argument('--radius-type', type=str, default='minor', choices=['circular', 'minor'],
                        help='Radius metric to plot: circular (from area) or minor (from ellipse), default: minor')
    parser.add_argument('--populations', type=Path, default=None,
                        help='Path to populations JSON file (from identify_cc_cg_populations.py) to filter analysis. '
                             'If provided, each population will be analyzed separately and plotted as individual data points.')
    parser.add_argument('--population-name', type=str, default=None, choices=['cc', 'cg'],
                        help='Specific population to analyze (default: analyze all populations in JSON)')

    args = parser.parse_args()

    # Determine mode based on presence of wildcards or number of matches
    import glob as glob_module

    pattern_2d = args.input
    pattern_3d = args.output

    # Check if patterns match multiple files (batch mode)
    matches_2d = glob_module.glob(pattern_2d, recursive=True)
    matches_3d = glob_module.glob(pattern_3d, recursive=True)

    is_batch_mode = (len(matches_2d) > 1 or len(matches_3d) > 1 or
                     '*' in pattern_2d or '*' in pattern_3d or
                     '?' in pattern_2d or '?' in pattern_3d)

    if is_batch_mode:
        # Batch mode: process all matching pairs
        if args.output_dir is None:
            parser.error("Batch mode requires output file/directory as third argument")

        output_path = args.output_dir

        # Determine if output is a file or directory
        if str(output_path).endswith('.png'):
            # Output is a specific file
            output_file = output_path
            output_file.parent.mkdir(parents=True, exist_ok=True)
        else:
            # Output is a directory - create default filename
            output_dir = output_path
            output_dir.mkdir(parents=True, exist_ok=True)
            output_file = output_dir / "combined_2d_vs_3d_comparison.png"

        pairs, unmatched_2d, unmatched_3d = find_matching_pairs(pattern_2d, pattern_3d)

        logger.info(f"\n{'='*80}")
        logger.info(f"Batch Mode")
        logger.info(f"{'='*80}")
        logger.info(f"2D pattern: {pattern_2d}")
        logger.info(f"3D pattern: {pattern_3d}")
        logger.info(f"Output file: {output_file}")
        logger.info(f"Radius type: {args.radius_type}")
        logger.info(f"Found {len(matches_2d)} 2D files, {len(matches_3d)} 3D files")
        logger.info(f"Matched pairs: {len(pairs)}")

        if unmatched_2d:
            logger.info(f"\nUnmatched 2D files (no corresponding 3D file):")
            for f in unmatched_2d:
                logger.info(f"  - {f.name}")

        if unmatched_3d:
            logger.info(f"\nUnmatched 3D files (no corresponding 2D file):")
            for f in unmatched_3d:
                logger.info(f"  - {f.name}")

        if len(pairs) == 0:
            logger.error(f"\nNo matching profile pairs found!")
            return

        logger.info(f"{'='*80}\n")

        # Collect all metrics from all samples
        all_metrics = []
        logger.info(f"Loading metrics from {len(pairs)} samples...\n")

        for i, (npz_2d, npz_3d, sample_name) in enumerate(pairs, 1):
            logger.info(f"[{i}/{len(pairs)}] Loading {sample_name}...")
            logger.info(f"  2D: {npz_2d.name}")
            logger.info(f"  3D: {npz_3d.name}")

            # Check if 2D file has population metadata
            population_labels = None
            try:
                data_2d = np.load(npz_2d)
                if 'population_name' in data_2d:
                    pop_name = str(data_2d['population_name'])
                    logger.info(f"  Population detected: {pop_name.upper()}")

                    # Load population labels from the same file or reconstruct from 3D
                    # We'll need to load from the populations JSON that's co-located with the MAT file
                    # For now, let's try to infer from the filename
                    import re
                    match = re.search(r'_(cc|cg)_slice_profiles', npz_2d.stem)
                    if match:
                        pop_name_from_file = match.group(1)
                        # Load the populations JSON to get labels
                        mat_base = npz_2d.stem.replace(f'_{pop_name_from_file}_slice_profiles', '')
                        # Look for populations JSON in same directory
                        pop_json_candidates = list(npz_2d.parent.glob(f"{mat_base}_populations.json"))
                        if pop_json_candidates:
                            pop_json = pop_json_candidates[0]
                            logger.info(f"  Loading population labels from {pop_json.name}")
                            with open(pop_json, 'r') as f:
                                pop_data = json.load(f)
                            for pop in pop_data['populations']:
                                if pop['name'].lower() == pop_name_from_file.lower():
                                    population_labels = set(pop['axon_labels'])
                                    logger.info(f"  Filtering 3D data to {len(population_labels)} axons")
                                    break
            except Exception as e:
                logger.warning(f"  Could not load population metadata: {e}")

            # Load metrics
            metrics_2d = load_2d_metrics(npz_2d, radius_type=args.radius_type)
            metrics_3d = load_3d_metrics(npz_3d, population_labels=population_labels)

            # Add to collection
            all_metrics.append((metrics_2d, metrics_3d, sample_name))

            # Print individual summary
            logger.info(f"  Arithmetic mean radius: 2D={metrics_2d['mean_radius']:.4f}, 3D={metrics_3d['mean_radius']:.4f}")
            logger.info(f"  Effective radius:       2D={metrics_2d['r_eff']:.4f}, 3D={metrics_3d['r_eff']:.4f}\n")

        # Create single combined plot with all samples
        logger.info(f"\n{'='*80}")
        logger.info(f"Creating combined plot with all {len(all_metrics)} samples...")
        logger.info(f"{'='*80}\n")

        # Generate title - check if any samples have population info
        has_populations = any('_CC' in name or '_CG' in name for _, _, name in all_metrics)
        if has_populations:
            title = "2D vs 3D Metrics Comparison (CC/CG Populations)"
        else:
            title = "2D vs 3D Metrics Comparison"

        plot_combined_2d_vs_3d_comparison(all_metrics, output_file, title)

        # Print overall summary statistics
        logger.info(f"\n{'='*80}")
        logger.info(f"SUMMARY STATISTICS (n={len(all_metrics)} samples)")
        logger.info(f"{'='*80}")

        # Compute mean differences across all samples
        mean_diffs = []
        eff_diffs = []

        for metrics_2d, metrics_3d, _ in all_metrics:
            if not np.isnan(metrics_3d['mean_radius']) and metrics_3d['mean_radius'] > 0:
                diff_pct = (metrics_2d['mean_radius'] - metrics_3d['mean_radius']) / metrics_3d['mean_radius'] * 100
                mean_diffs.append(diff_pct)

            if not np.isnan(metrics_3d['r_eff']) and metrics_3d['r_eff'] > 0:
                diff_pct = (metrics_2d['r_eff'] - metrics_3d['r_eff']) / metrics_3d['r_eff'] * 100
                eff_diffs.append(diff_pct)

        if mean_diffs:
            logger.info(f"\nArithmetic Mean Radius:")
            logger.info(f"  Average difference: {np.mean(mean_diffs):+.2f}% ± {np.std(mean_diffs):.2f}%")
            logger.info(f"  Range: {np.min(mean_diffs):+.2f}% to {np.max(mean_diffs):+.2f}%")

        if eff_diffs:
            logger.info(f"\nEffective Radius:")
            logger.info(f"  Average difference: {np.mean(eff_diffs):+.2f}% ± {np.std(eff_diffs):.2f}%")
            logger.info(f"  Range: {np.min(eff_diffs):+.2f}% to {np.max(eff_diffs):+.2f}%")

        logger.info(f"\n{'='*80}")
        logger.info(f"Combined plot saved to: {output_file}")
        logger.info(f"{'='*80}\n")

    else:
        # Single file mode
        npz_2d = Path(pattern_2d)
        npz_3d = Path(pattern_3d)
        output_file = args.output_dir

        if output_file is None:
            parser.error("Single file mode requires output PNG file as third argument")

        # Validate input files exist
        if not npz_2d.exists():
            parser.error(f"2D NPZ file not found: {npz_2d}")
        if not npz_3d.exists():
            parser.error(f"3D NPZ file not found: {npz_3d}")

        # Auto-detect sample name if not provided
        sample_name = args.sample_name
        if not sample_name:
            # Extract from filename (remove suffix)
            sample_name = npz_2d.stem.replace('_slice_profiles', '')

        logger.info(f"Single File Mode")
        logger.info(f"Processing sample: {sample_name}")
        logger.info(f"2D data: {npz_2d}")
        logger.info(f"3D data: {npz_3d}")
        logger.info(f"Radius type: {args.radius_type}")

        # Load population labels if provided
        population_labels = None
        if args.populations is not None:
            logger.info(f"Loading population labels from {args.populations}")
            population_labels = load_population_labels(args.populations, args.population_name)
            logger.info(f"Filtering to population '{args.population_name}' with {len(population_labels)} axons")

        # Load metrics
        metrics_2d = load_2d_metrics(npz_2d, radius_type=args.radius_type)
        metrics_3d = load_3d_metrics(npz_3d, population_labels=population_labels)

        # Create comparison plot
        plot_2d_vs_3d_comparison(metrics_2d, metrics_3d, output_file, sample_name)

        # Print summary
        logger.info("\n" + "="*60)
        logger.info("Comparison Summary")
        logger.info("="*60)
        logger.info(f"{'Metric':<25} {'2D Value':<15} {'3D Value':<15} {'Diff %':<10}")
        logger.info("-"*60)

        # Mean radius comparison
        if not np.isnan(metrics_3d['mean_radius']) and metrics_3d['mean_radius'] > 0:
            diff_mean_pct = (metrics_2d['mean_radius'] - metrics_3d['mean_radius']) / metrics_3d['mean_radius'] * 100
        else:
            diff_mean_pct = np.nan

        logger.info(f"{'Arithmetic Mean Radius':<25} "
                   f"{metrics_2d['mean_radius']:<15.4f} "
                   f"{metrics_3d['mean_radius']:<15.4f} "
                   f"{diff_mean_pct:>+9.1f}%")

        # Effective radius comparison
        if not np.isnan(metrics_3d['r_eff']) and metrics_3d['r_eff'] > 0:
            diff_eff_pct = (metrics_2d['r_eff'] - metrics_3d['r_eff']) / metrics_3d['r_eff'] * 100
        else:
            diff_eff_pct = np.nan

        logger.info(f"{'Effective Radius':<25} "
                   f"{metrics_2d['r_eff']:<15.4f} "
                   f"{metrics_3d['r_eff']:<15.4f} "
                   f"{diff_eff_pct:>+9.1f}%")

        logger.info("="*60 + "\n")


if __name__ == '__main__':
    main()
