"""
OME-Zarr I/O with multi-resolution pyramid support.

Provides functions to write 3D volumes as OME-Zarr (NGFF v0.4) with
multi-resolution pyramids, suitable for Neuroglancer visualization.

Supports two downsampling modes:
- 'nearest': Stride-based downsampling for segmentation labels
- 'mean': Local mean (box filter) for grayscale/intensity data

Example:
    import numpy as np
    from axonometry.zarr_io import write_ome_zarr_pyramid

    # Write segmentation with 4 pyramid levels
    labels = np.random.randint(0, 100, (200, 512, 512), dtype=np.uint16)
    write_ome_zarr_pyramid(
        labels, 'output.zarr',
        voxel_size_um=0.05,
        num_levels=4,
        downsample_mode='nearest',
    )

    # Write grayscale with local mean downsampling
    image = np.random.rand(200, 512, 512).astype(np.float32)
    write_ome_zarr_pyramid(
        image, 'output_image.zarr',
        voxel_size_um=0.05,
        num_levels=4,
        downsample_mode='mean',
    )
"""

import logging
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Union

import numpy as np
import zarr

logger = logging.getLogger(__name__)


def downsample_nearest(volume: np.ndarray, factor: int = 2) -> np.ndarray:
    """
    Downsample a 3D volume by striding (nearest-neighbor).

    Suitable for label/segmentation data where averaging is not meaningful.

    Args:
        volume: 3D array (Z, Y, X)
        factor: Downsampling factor (applied to all axes)

    Returns:
        Downsampled array
    """
    return volume[::factor, ::factor, ::factor].copy()


def downsample_mean(volume: np.ndarray, factor: int = 2) -> np.ndarray:
    """
    Downsample a 3D volume using local mean (box filter).

    Suitable for grayscale/intensity data.

    Args:
        volume: 3D array (Z, Y, X)
        factor: Downsampling factor (applied to all axes)

    Returns:
        Downsampled array (preserves dtype for integer types via rounding)
    """
    from skimage.transform import downscale_local_mean

    result = downscale_local_mean(volume, (factor, factor, factor))
    if np.issubdtype(volume.dtype, np.integer):
        return np.round(result).astype(volume.dtype)
    return result.astype(volume.dtype)


def compute_pyramid_shapes(
    base_shape: Tuple[int, ...],
    num_levels: int,
    factor: int = 2,
) -> List[Tuple[int, ...]]:
    """
    Compute shapes for all pyramid levels.

    Args:
        base_shape: Shape of level 0 (Z, Y, X)
        num_levels: Number of pyramid levels
        factor: Downsampling factor per level

    Returns:
        List of shapes, one per level
    """
    shapes = [base_shape]
    for _ in range(1, num_levels):
        prev = shapes[-1]
        shapes.append(tuple(max(1, s // factor) for s in prev))
    return shapes


def write_ome_zarr_pyramid(
    data: np.ndarray,
    output_path: Union[str, Path],
    voxel_size_um: Union[float, Tuple[float, float, float]] = 0.05,
    num_levels: int = 4,
    downsample_mode: str = 'nearest',
    chunk_size: int = 64,
    compression_level: int = 3,
    metadata: Optional[Dict] = None,
) -> Path:
    """
    Write a 3D volume as OME-Zarr with multi-resolution pyramid.

    Creates an OME-NGFF v0.4 compliant Zarr store with pyramid levels
    generated by successive downsampling.

    Args:
        data: 3D array (Z, Y, X) to write
        output_path: Path for output .zarr directory
        voxel_size_um: Voxel size in micrometers (scalar or (vz, vy, vx))
        num_levels: Number of pyramid levels (1=full only, 4=full+2x+4x+8x)
        downsample_mode: 'nearest' for labels, 'mean' for grayscale
        chunk_size: Target chunk size per dimension
        compression_level: Zstd compression level (0=none)
        metadata: Optional extra metadata to store in root attrs

    Returns:
        Path to created .zarr directory
    """
    import numcodecs

    output_path = Path(output_path)

    if downsample_mode not in ('nearest', 'mean'):
        raise ValueError(f"downsample_mode must be 'nearest' or 'mean', got {downsample_mode}")
    if num_levels < 1:
        raise ValueError(f"num_levels must be >= 1, got {num_levels}")

    # Parse voxel size
    if isinstance(voxel_size_um, (int, float)):
        voxel_size = (float(voxel_size_um),) * 3
    else:
        voxel_size = tuple(float(v) for v in voxel_size_um)

    # Select downsampler
    downsample_fn = downsample_nearest if downsample_mode == 'nearest' else downsample_mean

    # Create zarr v2 group (Neuroglancer compatible)
    root = zarr.open_group(str(output_path), mode='w', zarr_format=2)

    # Set up compression
    if compression_level > 0:
        compressor = numcodecs.Blosc(cname='zstd', clevel=compression_level, shuffle=numcodecs.Blosc.BITSHUFFLE)
    else:
        compressor = None

    # Build pyramid and write each level
    pyramid_shapes = compute_pyramid_shapes(data.shape, num_levels)
    current = data

    for level in range(num_levels):
        if level > 0:
            current = downsample_fn(current)

        level_chunks = tuple(min(chunk_size, s) for s in current.shape)

        arr = root.create_array(
            name=str(level),
            shape=current.shape,
            chunks=level_chunks,
            dtype=current.dtype,
            compressor=compressor,
            overwrite=True,
        )
        arr[:] = current

        logger.info(f"  Level {level}: {current.shape}, "
                     f"{current.nbytes / 1024**2:.1f} MB")

    # Write OME-NGFF v0.4 metadata
    datasets = []
    for level in range(num_levels):
        scale_factor = 2 ** level
        datasets.append({
            "path": str(level),
            "coordinateTransformations": [{
                "type": "scale",
                "scale": [v * scale_factor for v in voxel_size],
            }],
        })

    ome_metadata = {
        "version": "0.4",
        "name": output_path.stem,
        "axes": [
            {"name": "z", "type": "space", "unit": "micrometer"},
            {"name": "y", "type": "space", "unit": "micrometer"},
            {"name": "x", "type": "space", "unit": "micrometer"},
        ],
        "datasets": datasets,
        "type": downsample_mode,
        "metadata": {
            "original_shape": list(data.shape),
            **(metadata or {}),
        },
    }

    root.attrs["multiscales"] = [ome_metadata]

    logger.info(f"  Wrote OME-Zarr ({num_levels} levels) to {output_path}")

    return output_path
